version: '3'

services:
  mysql:
    image: mysql:8.0.25
    container_name: projeto-artia-mysql
    environment:
      MYSQL_DATABASE: projeto_artia
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
  app:
    container_name: projeto-backend-artia
    build:
      context: .
    links:
      - mysql
    command:
      - --spring.profiles.active=docker
    ports:
      - 8081:8081